# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=80)),
                ('to_number', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=300)),
                ('messageID', models.EmailField(max_length=80)),
                ('smsStatus', models.CharField(max_length=80)),
                ('from_country', models.CharField(max_length=20)),
                ('to_country', models.CharField(max_length=20)),
                ('forwarded_to', models.EmailField(max_length=70)),
            ],
        ),
    ]
