# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0002_auto_20180608_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=70)),
                ('to_email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=80)),
                ('MessageSid', models.CharField(max_length=80)),
            ],
        ),
    ]
