# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0007_auto_20180806_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=50)),
                ('buy', models.DecimalField(decimal_places=6, max_digits=8)),
                ('sell', models.DecimalField(decimal_places=6, max_digits=8)),
                ('route', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
            ],
        ),
    ]
