# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0009_auto_20180807_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='route',
            field=models.CharField(default='Twilio', max_length=80),
            preserve_default=False,
        ),
    ]
