# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0011_sms_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sms',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
