# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0012_auto_20180809_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageSid', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.EmailField(max_length=70)),
                ('to_number', models.EmailField(max_length=70)),
                ('user', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
