# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0013_auto_20190305_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.CharField(max_length=80)),
                ('to_number', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=1000)),
                ('MessageSid', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
        migrations.AlterField(
            model_name='sent',
            name='from_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sent',
            name='to_number',
            field=models.CharField(max_length=1000),
        ),
    ]
