# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0014_auto_20190305_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='message',
            field=models.CharField(default='Hello World', max_length=1000),
            preserve_default=False,
        ),
    ]
