# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0016_remove_received_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
