# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0018_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
