# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0020_queue_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='tag',
            field=models.CharField(default='Default', max_length=80),
            preserve_default=False,
        ),
    ]
