# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0021_sent_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=1000)),
                ('group', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='queue',
            name='from_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='to_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sent',
            name='from_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sent',
            name='to_number',
            field=models.CharField(max_length=20),
        ),
    ]
