# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0022_auto_20190311_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueBlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
