# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0023_queueblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueblast',
            name='message',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
