# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0024_auto_20190312_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueblast',
            old_name='name',
            new_name='tag',
        ),
    ]
