# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0025_auto_20190312_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueblast',
            name='status',
            field=models.CharField(default='Finish', max_length=80),
            preserve_default=False,
        ),
    ]
