# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0026_queueblast_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='goip',
            field=models.CharField(default='GoIPA01', max_length=80),
            preserve_default=False,
        ),
    ]
