# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0028_sent_goip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
