# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0029_auto_20190314_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
