# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0030_queue_datesent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sent',
        ),
    ]
