# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirvasmsapp', '0031_delete_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('provider', models.IntegerField()),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('alive', models.IntegerField()),
                ('num', models.CharField(max_length=30)),
                ('signal', models.IntegerField(blank=True, null=True)),
                ('gsm_status', models.CharField(max_length=30)),
                ('voip_status', models.CharField(max_length=30)),
                ('voip_state', models.CharField(max_length=30)),
                ('bal', models.FloatField(blank=True, null=True)),
                ('cellinfo', models.CharField(db_column='CELLINFO', max_length=160)),
                ('cgatt', models.CharField(db_column='CGATT', max_length=32)),
                ('bcch', models.CharField(db_column='BCCH', max_length=160)),
                ('bal_time', models.DateTimeField(blank=True, null=True)),
                ('keepalive_time', models.DateTimeField(blank=True, null=True)),
                ('gsm_login_time', models.DateTimeField(blank=True, null=True)),
                ('gsm_login_time_t', models.IntegerField()),
                ('keepalive_time_t', models.IntegerField()),
                ('remain_time', models.IntegerField()),
                ('imei', models.CharField(blank=True, max_length=15, null=True)),
                ('imsi', models.CharField(blank=True, max_length=32, null=True)),
                ('iccid', models.CharField(blank=True, max_length=32, null=True)),
                ('last_call_record_id', models.IntegerField()),
                ('remain_count', models.IntegerField()),
                ('count_limit', models.IntegerField()),
                ('remain_count_d', models.IntegerField()),
                ('count_limit_d', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('report_mail', models.CharField(max_length=64)),
                ('fwd_mail_enable', models.IntegerField()),
                ('report_http', models.CharField(max_length=64)),
                ('fwd_http_enable', models.IntegerField()),
                ('carrier', models.CharField(max_length=32)),
                ('auto_num_c', models.IntegerField()),
            ],
            options={
                'db_table': 'goip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(blank=True, max_length=30, null=True)),
                ('inter', models.CharField(blank=True, max_length=10, null=True)),
                ('local', models.CharField(blank=True, max_length=10, null=True)),
                ('recharge_ok_r', models.CharField(max_length=64)),
                ('auto_num_ussd', models.CharField(max_length=20)),
                ('num_prefix', models.CharField(max_length=20)),
                ('num_postfix', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=1000)),
            ],
        ),
    ]
